import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Layout from './provider';
import {Navbar} from '../components/pages/Navbar.js'

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='sticky top-0 bg-white z-10'>
      <Navbar />
      </div>
        <Layout>{children}</Layout>
        
      </body>
    </html>
  );
}